// export const expensesCatagoryArray = [
//   'Транспорт',
//   'Продукты',
//   'Здоровье',
//   'Алкоголь',
//   'Развлечения',
//   'Всё для дома',
//   'Техника',
//   'Комуналка, связь',
//   'Спорт, Хоби',
//   'Образование',
//   'Прочее',
// ];

export const incomeCatagoryArray = ['ЗП', 'Доп. доход'];

export const TRANSLATE_CATEGORIES = {
  Продукты: 'products',
  Алкоголь: 'alcohol',
  Развлечения: 'entertainment',
  Здоровье: 'healthy',
  Транспорт: 'transport',
  'Всё для дома': 'home',
  Техника: 'technic',
  'Комуналка, связь': 'communication',
  'Спорт, Хоби': 'hobby',
  Образование: 'education',
  Прочее: 'other',
  ЗП: 'salary',
  'Доп. доход': 'additional',

  products: 'products',
  home: 'home',
  entertainment: 'entertainment',
  healthy: 'healthy',
  transport: 'transport',
  alcohol: 'alcohol',
  technic: 'technic',
  communication: 'communication',
  hobby: 'hobby',
  education: 'education',
  other: 'other',
  salary: 'salary',
  additional: 'additional',
};
// export const TRANSLATE_CATEGORIES = {
//   products: 'Продукты',
//   alcohol: 'Алкоголь',
//   entertainment: 'Развлечения',
//   healthy: 'Здоровье',
//   transport: 'Транспорт',
//   home: 'Всё для дома',
//   technic: 'Техника',
//   communication: 'Комуналка, связь',
//   hobby: 'Спорт, Хоби',
//   education: 'Образование',
//   other: 'Прочее',
//   salary: 'ЗП',
//   additional: 'Доп. доход',

//   Продукты: 'products',
//   Алкоголь: 'alcohol',
//   Развлечения: 'entertainment',
//   Здоровье: 'healthy',
//   Транспорт: 'transport',
//   'Всё для дома': 'home',
//   Техника: 'technic',
//   'Комуналка, связь': 'communication',
//   'Спорт, Хоби': 'hobby',
//   Образование: 'education',
//   Прочее: 'other',
//   ЗП: 'salary',
//   'Доп. доход': 'additional',
// };

export const CATEGORYTYPE = {
  INCOME: 'income',
  EXPENSE: 'expense',
};
