export const TRANSLATE_CATEGORIES = {
  Продукты: 'products',
  Алкоголь: 'alcohol',
  Развлечения: 'entertainment',
  Здоровье: 'healthy',
  Транспорт: 'transport',
  'Всё для дома': 'home',
  Техника: 'technic',
  'Комуналка, связь': 'communication',
  'Спорт, Хоби': 'hobby',
  Образование: 'education',
  Прочее: 'other',
  ЗП: 'salary',
  'Доп. доход': 'additional',

  products: 'products',
  home: 'home',
  entertainment: 'entertainment',
  healthy: 'healthy',
  transport: 'transport',
  alcohol: 'alcohol',
  technic: 'technic',
  communication: 'communication',
  hobby: 'hobby',
  education: 'education',
  other: 'other',
  salary: 'salary',
  additional: 'additional',
};
export const TRANSLATE_CATEGORIES_FROM_BACK = {
  products: 'Продукты',
  alcohol: 'Алкоголь',
  entertainment: 'Развлечения',
  healthy: 'Здоровье',
  transport: 'Транспорт',
  home: 'Всё для дома',
  technic: 'Техника',
  communication: 'Комуналка, связь',
  hobby: 'Спорт, Хоби',
  education: 'Образование',
  other: 'Прочее',
  salary: 'ЗП',
  additional: 'Доп. доход',
};

export const CATEGORYTYPE = {
  INCOME: 'income',
  EXPENSE: 'expense',
};
